// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SlimFitGym.EFData;

#nullable disable

namespace SlimFitGym.EFData.Migrations
{
    [DbContext(typeof(SlimFitGymContext))]
    [Migration("20250206131806_BetterInit")]
    partial class BetterInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("SlimFitGym.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bicikli"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Futópad"
                        });
                });

            modelBuilder.Entity("SlimFitGym.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RecommendedPeople")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "Futós szoba",
                            RecommendedPeople = 15
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "Biciklizős Szoba",
                            RecommendedPeople = 10
                        });
                });

            modelBuilder.Entity("SlimFitGym.Models.RoomAndMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MachineCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomsAndMachines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MachineCount = 1,
                            MachineId = 1,
                            RoomId = 2
                        },
                        new
                        {
                            Id = 2,
                            MachineCount = 4,
                            MachineId = 2,
                            RoomId = 1
                        });
                });

            modelBuilder.Entity("SlimFitGym.Models.RoomAndMachine", b =>
                {
                    b.HasOne("SlimFitGym.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlimFitGym.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Room");
                });
#pragma warning restore 612, 618
        }
    }
}
