# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - SlimFitGymBackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/sariandras43/
        username: ${{ secrets.AzureAppService_ContainerUsername_19b350a0c1b34356b31cd878db9932f0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_73493273647a4402bcc2f3552fb22d82 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/sariandras43/${{ secrets.AzureAppService_ContainerUsername_19b350a0c1b34356b31cd878db9932f0 }}/sariandras43/slimfitgymbackend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'SlimFitGymBackend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0469e21e3b97450491dc70230a8d7ff2 }}
        images: 'ghcr.io/sariandras43/${{ secrets.AzureAppService_ContainerUsername_19b350a0c1b34356b31cd878db9932f0 }}/sariandras43/slimfitgymbackend:${{ github.sha }}'